import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {cn} from "@/lib/utils";

import "./globals.css";
import {QueryProvider} from "@/components/query-provider";
import {Toaster} from "@/components/ui/sonner";
import { ThemeProvider, useTheme } from "./context/theme-context";

const inter = Inter({subsets: ["latin"]});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { theme, customColors } = useTheme();

    return (
        <ThemeProvider>
        <html lang="en">
        <body
            data-theme={theme}
            className={cn(inter.className, "antialiased min-h-screen")}
        >
            {theme === 'custom' && (
                <style>
                    {`
                    :root {
                        --custom-background: ${customColors.background};
                        --custom-text: ${customColors.text};
                    }
                    `}
                </style>
            )}
        <QueryProvider>
            <Toaster/>
            {children}
        </QueryProvider>
        </body>
        </html>
        </ThemeProvider>
    );

}
