version: "3.9"

services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "https://app:3000" # Use the service name 'app' as the hostname
      - "--domain=tolerant-grown-mallard.ngrok-free.app"
    environment:
      NGROK_AUTHTOKEN: 2ti6vgfBBn8dXRTzT79Pmxl1VR6_22x2oKB7B8fS9JJvmMNVJ
    ports:
      - "4040:4040" # Expose ngrok's web interface
    networks:
      - app-network

  app:
    build:
      dockerfile: ./Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    environment:
      - inDocker=true
      - NEXT_PUBLIC_APP_URL=https://tolerant-grown-mallard.ngrok-free.app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge